[General]
bypass-system = true
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
fallback-dns-server = 223.5.5.5, 119.29.29.29, 1.1.1.1
ipv6 = false

[Rule]
AND,((PROTOCOL,UDP),(DEST-PORT,443),(NOT,((GEOIP,CN)))),REJECT-NO-DROP
DEST-PORT,993,DIRECT

RULE-SET,https://github.dytst.cn/https://raw.githubusercontent.com/jamessochingzz/rules/refs/heads/main/Direct.txt,DIRECT
RULE-SET,https://github.dytst.cn/https://raw.githubusercontent.com/666OS/rules/refs/heads/release/surge/Private.txt,DIRECT
RULE-SET,https://github.dytst.cn/https://raw.githubusercontent.com/666OS/rules/refs/heads/release/surge/China.txt,DIRECT

FINAL,PROXY